version: '3'

networks:
  qualibrate:
    driver: bridge
    ipam:
      config:
        - subnet: 10.3.0.0/16
          


services: 
  api-doc-ngnix:
    build:
      context: .
      dockerfile: ApiDocDockerfile
    links:
      - qualibrate-rest-api-dev
    ports:
      - 8085:80
    networks:
      qualibrate:
        aliases:
          - web.qualibrate.com

  qualibrate-rest-api-dev:
    build:
      context: .
      dockerfile: ApiDockerfile
    links:
      - "docker-mysql:dbHost"
    ports:
      - 8080:8080
    environment:
      - DBHOST=docker-mysql
    networks:
      qualibrate:
        aliases:
          - api.qualibrate.com  
      
  docker-mysql:
    image: mysql:5.7.21
    hostname: docker-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=qualibrate
    networks:
      qualibrate:
        aliases:
          - db.qualibrate.com
  portainer:
    container_name: qualibrate-monitor
    image: portainer/portainer
    restart: always
    ports:
     - '9000:9000'
    volumes: 
     - '/var/run/docker.sock:/var/run/docker.sock'
    
    networks:
      qualibrate:
        aliases:
          - portainer.qualibrate.com
