version: '3'

services: 
  api-doc-ngnix:
    build:
      context: .
      dockerfile: ApiDocDockerfile
    links:
      - qualibrate-rest-api-dev
    ports:
      - 8085:80

  qualibrate-rest-api-dev:
    build:
      context: .
      dockerfile: ApiDockerfile
    links:
      - "docker-mysql:dbHost"
    ports:
      - 8080:8080
    environment:
      - DBHOST=docker-mysql
      - SPRING_PROFILES_ACTIVE=dev
  docker-mysql:
    image: mysql:5.7.21
    hostname: docker-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=qualibrate
