branch-defaults:
  master:
    environment: qualibrate-java-api-qa
deploy:
  artifact: build/libs/qualibrate-java-api-0.0.1-SNAPSHOT.jar
global:
  application_name: qualibrate-java-api
  branch: null
  default_ec2_keyname: kru-qualibrate-api
  default_platform: Java 8
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
