
---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db.qualibrate.com:3306/qualibrate?nullNamePatternMatchesAll=true&useSSL=false&rewriteBatchedStatement=trye&useUnicode=true&characterEncoding=utf8
    username: root
    password: "root"
    validation-query: SELECT 1
    test-on-borrow: true
  jpa:
    hibernate:
      dialect: org.hivernate.dialect.MySQL5Dialect
      ddl-auto: none
    show-sql: true
---
spring:
  datasource:
    url: jdbc:mysql://db.qualibrate.com:3306/qualibrate?useSSL=false&nullNamePatternMatchesAll=true&rewriteBatchedStatement=trye&useUnicode=true&characterEncoding=utf8
  profiles: production
liquibase:
  contexts: production
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qualibrate?useSSL=false&rewriteBatchedStatement=trye&useUnicode=true&characterEncoding=utf8
  profiles: local
liquibase:
  contexts: local
---
spring:
  profiles: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:qualibrate;MODE=MySQL
  jpa:
    show-sql: false
liquibase:
  contexts: test